# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TransData_c <- function(bfile, pBigMat, maxLine, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_KAML_TransData_c`, bfile, pBigMat, maxLine, threads, verbose))
}

