# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaston_brent <- function(Y, X, p_, Sigma, U, min_h2, max_h2, tol, verbose) {
    .Call(`_KAML_gaston_brent`, Y, X, p_, Sigma, U, min_h2, max_h2, tol, verbose)
}

crossprodcpp <- function(X) {
    .Call(`_KAML_crossprodcpp`, X)
}

geninv <- function(GG) {
    .Call(`_KAML_geninv`, GG)
}

TransData_c <- function(bfile, pBigMat, maxLine, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_KAML_TransData_c`, bfile, pBigMat, maxLine, threads, verbose))
}

impute_marker <- function(pBigMat, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_KAML_impute_marker`, pBigMat, threads, verbose))
}

hasNA <- function(pBigMat, threads = 0L) {
    .Call(`_KAML_hasNA`, pBigMat, threads)
}

glm_c <- function(y, X, pBigMat, barhead = "GWAS in process", verbose = TRUE, threads = 0L) {
    .Call(`_KAML_glm_c`, y, X, pBigMat, barhead, verbose, threads)
}

mlm_c <- function(y, X, U, vgs, pBigMat, barhead = "GWAS in process", verbose = TRUE, threads = 0L) {
    .Call(`_KAML_mlm_c`, y, X, U, vgs, pBigMat, barhead, verbose, threads)
}

BigStat <- function(pBigMat, threads = 0L) {
    .Call(`_KAML_BigStat`, pBigMat, threads)
}

kin_cal_m <- function(pBigMat, SUM = NULL, scale = FALSE, wt = NULL, threads = 0L, barhead = " Computing in process", verbose = TRUE) {
    .Call(`_KAML_kin_cal_m`, pBigMat, SUM, scale, wt, threads, barhead, verbose)
}

kin_cal_s <- function(pBigMat, SUM = NULL, scale = FALSE, wt = NULL, threads = 0L, mkl = FALSE, barhead = " Computing in process", verbose = TRUE) {
    .Call(`_KAML_kin_cal_s`, pBigMat, SUM, scale, wt, threads, mkl, barhead, verbose)
}

